spring:
  application:
    name: encoding-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: encoding-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: com.netflix.encoding_service.event.VideoUploadedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

# AWS Configuration
aws:
  access-key: ${AWS_ACCESS_KEY:YOUR_AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY:YOUR_AWS_SECRET_KEY}
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket-name: ${AWS_BUCKET_NAME:netflix-streaming-videos}

# FFmpeg Configuration
ffmpeg:
  path: ${FFMPEG_PATH:C:/ffmpeg/ffmpeg.exe}

# Temp directory for encoding
encoding:
  temp-dir: ${TEMP_DIR:C:/temp/encoding}

management:
  endpoints:
    web:
      exposure:
        include: health,info
